spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
      format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8080
  servlet:
    context-path: /bank

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

age-of-majority: 18

spring.cloud.openfeign.client.config.rateClient.url: https://api.nbp.pl/api/exchangerates/rates/a/

resilience4j.ratelimiter:
  instances:
    getAccountByAccountNumber:
      limit-for-period: 5
      limit-refresh-period: 1m
      timeout-duration: 0
