spring:
  datasource:
    url: jdbc:postgresql://localhost/marcin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      format_sql: true
    defer-datasource-initialization: true
    database-platform: PostgreSQL
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  logging:
    pattern:
      console: "%msg%n"
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO
server:
  servlet:
    context-path: /bank
age-of-majority: 18