spring:
  datasource:
    url: jdbc:postgresql://localhost/marcin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

  cloud:
    openfeign:
      client:
        config:
          rateClient:
            url: https://api.nbp.pl/api/exchangerates/rates/a/

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

server:
  servlet:
    context-path: /bank

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

age-of-majority: 21

resilience4j.ratelimiter:
  instances:
    getAccountByAccountNumber:
      limit-for-period: 5
      limit-refresh-period: 1m
      timeout-duration: 0
