spring:
#  profiles:
#    active: usa
  datasource:
    url: jdbc:postgresql://localhost/marcin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
      allow-bean-definition-overriding: true
  jpa:
    properties:
      format_sql: true
    defer-datasource-initialization: true
#    database-platform: PostgreSQL
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  logging:
    pattern:
      console: "%msg%n"
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO
      org.springframework.security: DEBUG


#  output:
#    ansi:
#      enabled: DETECT
server:
  servlet:
    context-path: /bank

age-of-majority: 18

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

#springdoc:
#  swagger-ui:
#    path: /swagger-something.html